### ISSUE TITLE
Use `clap` for CLI

### ISSUE THREAD

**Issue by ok-nick** [Razer-Linux/razer-laptop-control-no-dkms#29]
Would make the interface much more idiomatic, clear, colorful, and convenient. `clap` is usually referred to as the "standard" for Rust CLIs.

**Comment by phush0** [comment]
You are free to make pr with your proposal with some screenshots before and after

**Comment by poisson-fish** [comment]
https://github.com/phush0/razer-laptop-control-no-dkms/pull/33

**Comment by phush0** [comment]
please rebase on main
