### ISSUE TITLE
Manually-specified configuration file

### ISSUE THREAD

**Issue by ok-nick** [Razer-Linux/razer-laptop-control-no-dkms#32]
It seems like a config file does exist but [it's only used internally](https://github.com/phush0/razer-laptop-control-no-dkms/blob/master/razer_control_gui/src/config.rs#L5-L6). It would be great if we could expose this through the CLI and probably best to store it in `~/.config` by default. There should also be a system-level configuration in `/etc`.

This would be a great feature to integrate with the nix flake.

**Comment by phush0** [comment]
PR is welcomed
