### ISSUE TITLE
Referencing this tool on an ongoing issue with Thermald over on the Ubuntu bug tracker

### ISSUE THREAD

**Issue by biblicabeebli** [Razer-Linux/razer-laptop-control-no-dkms#37]
https://bugs.launchpad.net/ubuntu/+source/linux/+bug/2026658

I've found this tool helpful in dealing with substantial performance issues with a Razer 17 2022 laptop, the issue was introduced in Ubuntu 23.04.  Current fix is to uninstall Thermald, your tool also resolves the issue on some at least one of the cpu power modes, exhibits different behavior on others, though the buggy interaction occurs on at least one.

The primary bug is that the max cpu speed becomes locked to 400Mhz across all cores after a brief instance of heavy use.

One thing I've noticed is that "Balanced" mode does not seem to have the same behavior as whatever the power mode applied at boot is, so I am wondering if you have any insight about that.

**Comment by phush0** [comment]
I read all the Ubuntu thread and my opinion is uninstall thermald, as for Razer laptop it does nothing positive, same for tlp. Control on the Razer laptops is through EC, that's why this app exist. Setting various bits in kernel or using other software will just hinder performance or brake everything. On some of the models (if not all) ACPII is broken, because Razer will always target Windows in mind. Try remove thermald and tlp and try again with your endeavors in Linux world.

**Comment by biblicabeebli** [comment]
Thanks for the input, I'll update the issue with that.

If you wouldn't mind, for my personal knowledge, what does EC refer to? (I've seen it around in this kind of context but I can't work out how to google it.)

**Comment by phush0** [comment]
EC stands for Embedded Controller

**Comment by bochen87** [comment]
Hi, I ran into the same issue with my razer blade 2022 model. The CPU get's stuck at 400 MHz when waking up from sleep state, which is really annoying. So if I understand correctly, the suggested fix is to uninstall thermald and tlp and to install this app? Do I need to make any settings or it "just works" after installing?

**Comment by biblicabeebli** [comment]
This gives you more control, at the level of the windows razer control panel options

Thermald doesn't work correctly and is the cause of my throttling so uninstalling fixed it. I posted a bug on ubuntu forums, commented here to see if the author had any wisdom to share and so it could get fixed upstream.

Start with uninstalling thermald.

**Comment by bochen87** [comment]
> This gives you more control, at the level of the windows razer control panel options
> 
> Thermald doesn't work correctly and is the cause of my throttling so uninstalling fixed it. I posted a bug on ubuntu forums, commented here to see if the author had any wisdom to share and so it could get fixed upstream.
> 
> Start with uninstalling thermald.

Yeah, I saw your bug report, which led me here. So I also uninstalled thermald and installed openrazr + this app. Seems to have fixed the issue :-)

**Comment by phush0** [comment]
thermald and tlp are no go for AMD laptops just remove them

**Comment by biblicabeebli** [comment]
These are not AMD laptops.
