### ISSUE TITLE
[BUG] daemon stops working if tried to apply static gradient

### ISSUE THREAD

**Issue by l3ifk** [Razer-Linux/razer-laptop-control-no-dkms#71]
**Daemon status log**
post result form `systemctl --user status razercontrol.service`
```
× razercontrol.service - Razer laptop control daemon
     Loaded: loaded (/etc/xdg/systemd/user/razercontrol.service; enabled; preset: enabled)
     Active: failed (Result: exit-code) since Mon 2024-07-08 17:22:36 CEST; 22s ago
   Duration: 4min 14.196s
    Process: 2573 ExecStart=/usr/share/razercontrol/daemon (code=exited, status=101)
   Main PID: 2573 (code=exited, status=101)
        CPU: 879ms

Jul 08 17:18:23 blade-14 daemon[2573]: supported device: "Blade 2022 14"
Jul 08 17:18:23 blade-14 daemon[2573]: Online AC0: true
Jul 08 17:18:22 blade-14 systemd[2555]: Started razercontrol.service - Razer laptop control daemon.
Jul 08 17:22:36 blade-14 daemon[2573]: REQ: SetEffect { name: "static_gradient", params: [80, 9, 1>
Jul 08 17:22:36 blade-14 daemon[2573]: Something went wrong! Removing the socket path
Jul 08 17:22:36 blade-14 daemon[2573]: thread 'main' panicked at src/kbd/effects.rs:77:71:
Jul 08 17:22:36 blade-14 daemon[2573]: index out of bounds: the len is 6 but the index is 6
Jul 08 17:22:36 blade-14 daemon[2573]: note: run with `RUST_BACKTRACE=1` environment variable to d>
Jul 08 17:22:36 blade-14 systemd[2555]: razercontrol.service: Main process exited, code=exited, st>
Jul 08 17:22:36 blade-14 systemd[2555]: razercontrol.service: Failed with result 'exit-code'.

```
**Describe the bug**
every time I try to apply a static daemon with `razer-cli effect static-gradient 80 9 143 141 108 171` the daemon fails and I have to restart it with systemctl. Other effects like the standard effects work fine btw.
**To Reproduce**
- use `razer-cli effect static-gradient` with any numbers.
```
No response from daemon
Unknown daemon error!
```
This is the response and upon further tries to use razer-cli I get `Error. Socket doesn't exit. Is daemon running?` and I have to restart the daemon.

**Expected behavior**
Change the color of the keyboard according to the input.

I have a Razer Blade 14 2022 btw.

**Comment by JosuGZ** [comment]
For some reason they have 7 arguments, and I'm not sure whether the 7th has some use or it is just a mistake that has never been tested, but I have tried this fix and it works. The effect is cool :)
